@host = http://localhost:9000/addNew

###

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "bname": "Programming with C",
    "issuer": "Abdul",
    "dueDate": "2021-12-10"
}

###

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "bname": "Python Data Structures",
    "issuer": "Binu",
    "dueDate": "2021-12-19"
}

###

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "bname": "Discrete Mathematics",
    "issuer": "Charu",
    "dueDate": "2021-12-17"
}

###

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "bname": "Android App Development",
    "issuer": "Divya",
    "dueDate": "2021-12-23"
}

###

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "bname": "Web Development",
    "issuer": "Eshan",
    "dueDate": "2021-12-25"
}